#!/usr/bin/env bash
set -uo pipefail;

####################################
# Ensure we can execute standalone #
####################################

function early_death() {
  echo "[FATAL] ${0}: ${1}" >&2;
  exit 1;
};

if [ -z "${TGENV_ROOT:-""}" ]; then
  # http://stackoverflow.com/questions/1055671/how-can-i-get-the-behavior-of-gnus-readlink-f-on-a-mac
  readlink_f() {
    local target_file="${1}";
    local file_name;

    while [ "${target_file}" != "" ]; do
      cd "$(dirname ${target_file})" || early_death "Failed to 'cd \$(dirname ${target_file})' while trying to determine TGENV_ROOT";
      file_name="$(basename "${target_file}")" || early_death "Failed to 'basename \"${target_file}\"' while trying to determine TGENV_ROOT";
      target_file="$(readlink "${file_name}")";
    done;

    echo "$(pwd -P)/${file_name}";
  };

  TGENV_ROOT="$(cd "$(dirname "$(readlink_f "${0}")")/.." && pwd)";
  [ -n "${TGENV_ROOT}" ] || early_death "Failed to 'cd \"\$(dirname \"\$(readlink_f \"${0}\")\")/..\" && pwd' while trying to determine TGENV_ROOT";
else
  TGENV_ROOT="${TGENV_ROOT%/}";
fi;
export TGENV_ROOT;

if [ -n "${TGENV_HELPERS:-""}" ]; then
  log 'debug' 'TGENV_HELPERS is set, not sourcing helpers again';
else
  [ "${TGENV_DEBUG:-0}" -gt 0 ] && echo "[DEBUG] Sourcing helpers from ${TGENV_ROOT}/lib/helpers.sh";
  if source "${TGENV_ROOT}/lib/helpers.sh"; then
    log 'debug' 'Helpers sourced successfully';
  else
    early_death "Failed to source helpers from ${TGENV_ROOT}/lib/helpers.sh";
  fi;
fi;

# Ensure libexec and bin are in $PATH
for dir in libexec bin; do
  case ":${PATH}:" in
    *:${TGENV_ROOT}/${dir}:*) log 'debug' "\$PATH already contains '${TGENV_ROOT}/${dir}', not adding it again";;
    *)
      log 'debug' "\$PATH does not contain '${TGENV_ROOT}/${dir}', prepending and exporting it now";
      export PATH="${TGENV_ROOT}/${dir}:${PATH}";
      ;;
  esac;
done;

#####################
# Begin Script Body #
#####################

[ "${#}" -gt 1 ] && log 'error' 'usage: tgenv use [<version>]';

[ -d "${TGENV_ROOT}/versions" ] \
  || log 'error' 'No versions of terragrunt installed. Please install one with: tgenv install';

declare requested="${1:-""}";

log debug "Resolving version with: tgenv-resolve-version ${requested}";
declare resolved="$(tgenv-resolve-version ${requested})";

declare version="${resolved%%\:*}";
declare regex="${resolved##*\:}";

log 'debug' "Searching ${TGENV_ROOT}/versions for latest version matching ${regex}";
declare version="$(\find "${TGENV_ROOT}/versions" -type d -exec basename {} \; \
  | tail -n +2 \
  | sort -t'.' -k 1nr,1 -k 2nr,2 -k 3nr,3 \
  | grep -e "${regex}" \
  | head -n 1
)";

[ -n "${version}" ] \
  && log 'debug' "Found version: ${version}" \
  || log 'error' "No installed versions of terragrunt matched '${1}'";

target_path="${TGENV_ROOT}/versions/${version}";
[ -f "${target_path}/terragrunt" ] \
  || log 'error' "Version directory for ${version} is present, but the terragrunt binary is not! Manual intervention required.";
[ -x "${target_path}/terragrunt" ] \
  || log 'error' "Version directory for ${version} is present, but the terragrunt binary is not executable! Manual intervention required.";

log 'info' "Switching default version to v${version}";
version_file="${TGENV_ROOT}/version";
log 'debug' "Writing \"${version}\" to \"${version_file}\"";
echo "${version}" > "${version_file}" \
  || log 'error' "Switch to v${version} failed";

if [ "${version_file}" != "$(tgenv-version-file)" ]; then
  log 'warn' "Default version file overridden by $(tgenv-version-file), changing the default version has no effect";
fi;

terragrunt --version 1>/dev/null \
  || log 'error' "'terragrunt --version' failed. Something is seriously wrong";
log 'info' "Switching completed";
