#!/usr/bin/env bash
# Summary: Show the currently-selected terragrunt version

set -uo pipefail;

####################################
# Ensure we can execute standalone #
####################################

function early_death() {
  echo "[FATAL] ${0}: ${1}" >&2;
  exit 1;
};

if [ -z "${TGENV_ROOT:-""}" ]; then
  # http://stackoverflow.com/questions/1055671/how-can-i-get-the-behavior-of-gnus-readlink-f-on-a-mac
  readlink_f() {
    local target_file="${1}";
    local file_name;

    while [ "${target_file}" != "" ]; do
      cd "$(dirname ${target_file})" || early_death "Failed to 'cd \$(dirname ${target_file})' while trying to determine TGENV_ROOT";
      file_name="$(basename "${target_file}")" || early_death "Failed to 'basename \"${target_file}\"' while trying to determine TGENV_ROOT";
      target_file="$(readlink "${file_name}")";
    done;

    echo "$(pwd -P)/${file_name}";
  };

  TGENV_ROOT="$(cd "$(dirname "$(readlink_f "${0}")")/.." && pwd)";
  [ -n "${TGENV_ROOT}" ] || early_death "Failed to 'cd \"\$(dirname \"\$(readlink_f \"${0}\")\")/..\" && pwd' while trying to determine TGENV_ROOT";
else
  TGENV_ROOT="${TGENV_ROOT%/}";
fi;
export TGENV_ROOT;

if [ -n "${TGENV_HELPERS:-""}" ]; then
  log 'debug' 'TGENV_HELPERS is set, not sourcing helpers again';
else
  [ "${TGENV_DEBUG:-0}" -gt 0 ] && echo "[DEBUG] Sourcing helpers from ${TGENV_ROOT}/lib/helpers.sh";
  if source "${TGENV_ROOT}/lib/helpers.sh"; then
    log 'debug' 'Helpers sourced successfully';
  else
    early_death "Failed to source helpers from ${TGENV_ROOT}/lib/helpers.sh";
  fi;
fi;

# Ensure libexec and bin are in $PATH
for dir in libexec bin; do
  case ":${PATH}:" in
    *:${TGENV_ROOT}/${dir}:*) log 'debug' "\$PATH already contains '${TGENV_ROOT}/${dir}', not adding it again";;
    *)
      log 'debug' "\$PATH does not contain '${TGENV_ROOT}/${dir}', prepending and exporting it now";
      export PATH="${TGENV_ROOT}/${dir}:${PATH}";
      ;;
  esac;
done;

#####################
# Begin Script Body #
#####################

[ -d "${TGENV_ROOT}/versions" ] \
  || log 'error' 'No versions of terragrunt installed. Please install one with: tgenv install';

TGENV_VERSION_FILE="$(tgenv-version-file)" \
  && log 'debug' "TGENV_VERSION_FILE retrieved from tgenv-version-file: ${TGENV_VERSION_FILE}" \
  || log 'error' 'Failed to retrieve TGENV_VERSION_FILE from tgenv-version-file';

TGENV_VERSION="$(cat "${TGENV_VERSION_FILE}" || true)" \
  && log 'debug' "TGENV_VERSION specified in TGENV_VERSION_FILE: ${TGENV_VERSION}";

if [[ "${TGENV_VERSION}" =~ ^latest.*$ ]]; then
  log 'debug' "TGENV_VERSION uses 'latest' keyword: ${TGENV_VERSION}";

  if [[ "${TGENV_VERSION}" =~ ^latest\:.*$ ]]; then
    regex="${TGENV_VERSION##*\:}";
    log 'debug' "'latest' keyword uses regex: ${regex}";
  else
    regex='.*'; # Just saves a seperate command below without the grep
    log 'debug' "'latest' keyword does not use regex";
  fi;

  version="$(\find "${TGENV_ROOT}/versions" -type d -exec basename {} \; \
    | tail -n +2 \
    | sort -t'.' -k 1nr,1 -k 2nr,2 -k 3nr,3 \
    | grep -e "${regex}" \
    | head -n 1)";

  if [ -n "${version}" ]; then
    log 'debug' "Version selected: ${version}";
    TGENV_VERSION="${version}"
  else
    log 'error' "No installed versions of terragrunt matched '${TGENV_VERSION}'";
  fi;

else
  log 'debug' 'TGENV_VERSION does not use "latest" keyword';
fi;

[ -z "${TGENV_VERSION}" ] \
  && log 'error' "Version could not be resolved (set by ${TGENV_VERSION_FILE} or tgenv use <version>)";

if [ ! -d "${TGENV_ROOT}/versions/${TGENV_VERSION}" ]; then
  log 'debug' "version '${TGENV_VERSION}' is not installed (set by ${TGENV_VERSION_FILE})";
fi;

echo "${TGENV_VERSION}";
